### PR TITLE
Make json valid

### PR DESCRIPTION
**Pull request by Macleykun**
Missing comma, looking forward to try it out!!

### CODE REVIEW

**Comment by Macleykun** [comment]
Seems to return a different error
IMG_3531
But atleast the PR improves it somewhat :)

**Comment by arichornlover** [comment]
I’m so sorry about that, I had no idea

**Comment by Macleykun** [comment]
No worries :) I do look forward to the SideStore version!
________________________________
Van: arichorn ***@***.***>
Verzonden: Wednesday, July 5, 2023 10:29:51 PM
Aan: arichorn/arichorn.github.io ***@***.***>
CC: Macley ***@***.***>; Author ***@***.***>
Onderwerp: Re: [arichorn/arichorn.github.io] Make json valid (PR #2)


Merged #2<https://github.com/arichorn/arichorn.github.io/pull/2> into main.

**Comment by arichornlover** [comment]
I hope it works, I’m just disappointed that it wasn’t compatible with both AltStore & SideStore

**Pull request merged**
