### PR TITLE
Make it work on Sidestore (and Altstore?)

### PR DESCRIPTION
**Pull request by Macleykun**
Hello there!

i saw it wasn't fixed yet, so i went and compared the working apps.json with the others. All this time it was this what caused to break the entire json:
```json
      "screenshotURLs": [
        ""
      ],
```
Removing this part made it work.

Do note the following:
for YouTubeRebornPlus the bundleIdentifier has to be unique it seems. For now i named it: com.google.ios.youtubethishastobeunique but i'm assuming this won't work for downloading, but perhaps you can give it a more appropiate name?

I did remove the versionDescription from YouTubeRebornPlus as there was none provided in the other jsons.

Do try it out in Sidestore/Altstore: 
https://raw.githubusercontent.com/Macleykun/arichorn.github.io/merge-jsons/apps.json or check it out here: https://altsource.by.lao.sb/browse/?source=https%3A%2F%2Fraw.githubusercontent.com%2FMacleykun%2Farichorn.github.io%2Fmerge-jsons%2Fapps.json

I hope this will make it easier for you and the users to see what youtube versions are out there, and to keep them easier up-to-date for everyone :)

### CODE REVIEW

**Comment by Macleykun** [comment]
oh and this will fix this issue ofc https://github.com/arichorn/arichorn.github.io/issues/1

**Comment by arichornlover** [comment]
I had to revert. due to the following reasons.
all of the tweaks were merged & YouTubeRebornPlus’s was not supposed to look like YouTube Reborn.

I’m not being mean about your pull request, it was pretty good but I was only against some of the changes that didn’t feel right for the AltSource, I will merge the other changes that fixes the problem for SideStore

Edit: I added it back in, I’m sorry but hopefully it works for SideStore.

**Comment by Macleykun** [comment]
Just tested it and it works (apps.json) :) and don't worry about it! I do wonder if it's any use to keep the other .json's, as it's now all merged into one.

Perhaps in the future, i can look into making stuff a bit more automatic with ci/cd's. But i'm not sure how updating exactly is done yet from the apps.json, but i'll keep an eye on that.

(thinking about github actions with sed to check when a new release is out from the different youtube versions you maintain and update the json with the new url's).

enjoy the weekend :)

**Comment by Macleykun** [comment]
it seems that installing youtubereborn gives this issue:
IMG_0894

Perhaps it's b/c of this line or should smth else be changed?
https://github.com/arichorn/arichorn.github.io/blob/main/apps.json#L43

**Pull request merged**
